// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using WearManager.Context;
using WearManager.Enums;

namespace WearManager.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class MainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("WearManager.Models.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand");

                    b.Property<string>("Description");

                    b.Property<float>("Distance");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Bikes");
                });

            modelBuilder.Entity("WearManager.Models.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AlternativeId");

                    b.Property<int?>("BikeId");

                    b.Property<string>("Brand");

                    b.Property<string>("Description");

                    b.Property<float>("Distance");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("AlternativeId");

                    b.HasIndex("BikeId");

                    b.ToTable("Part");
                });

            modelBuilder.Entity("WearManager.Models.Wheel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand");

                    b.Property<int?>("CogSetId");

                    b.Property<string>("Description");

                    b.Property<float>("Distance");

                    b.Property<string>("Name");

                    b.Property<string>("Set");

                    b.Property<int?>("TireId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("CogSetId");

                    b.HasIndex("TireId");

                    b.ToTable("Wheels");
                });

            modelBuilder.Entity("WearManager.Models.Part", b =>
                {
                    b.HasOne("WearManager.Models.Part", "Alternative")
                        .WithMany()
                        .HasForeignKey("AlternativeId");

                    b.HasOne("WearManager.Models.Bike")
                        .WithMany("Parts")
                        .HasForeignKey("BikeId");
                });

            modelBuilder.Entity("WearManager.Models.Wheel", b =>
                {
                    b.HasOne("WearManager.Models.Part", "CogSet")
                        .WithMany()
                        .HasForeignKey("CogSetId");

                    b.HasOne("WearManager.Models.Part", "Tire")
                        .WithMany()
                        .HasForeignKey("TireId");
                });
#pragma warning restore 612, 618
        }
    }
}
